import { PrismaClient, GenderLabel } from '@prisma/client';

const prisma = new PrismaClient();

const mensSizes = ['S', 'M', 'L', 'XL', '28', '30', '32', '40', '26.0', '27.0'];
const womensSizes = ['XS', 'S', 'M', 'L', '24', '26', '28', '38', '23.0', '24.0'];
const unisexSizes = ['XS', 'S', 'M', 'L', 'XL', '25.0', '26.0', '27.0', '28.0'];

const imagePool = [
  'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=800&q=80',
  'https://images.unsplash.com/photo-1523381210434-271e8be1f52b?auto=format&fit=crop&w=800&q=80',
  'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=800&q=80',
  'https://images.unsplash.com/photo-1462396881884-de2c07cb95ed?auto=format&fit=crop&w=800&q=80',
  'https://images.unsplash.com/photo-1503341455253-b2e723bb3dbb?auto=format&fit=crop&w=800&q=80',
  'https://images.unsplash.com/photo-1487412912498-0447578fcca8?auto=format&fit=crop&w=800&q=80',
  'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
  'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=800&q=80',
  'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?auto=format&fit=crop&w=800&q=80',
  'https://images.unsplash.com/photo-1460881680858-30d872d5b530?auto=format&fit=crop&w=800&q=80',
  'https://images.unsplash.com/photo-1520962918287-7448c2878f65?auto=format&fit=crop&w=800&q=80',
  'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=800&q=80'
];

const products = [
  {
    name: 'Aurora Satin Shirt',
    brand: 'Lumen',
    genderLabel: 'womens' as GenderLabel,
    collection: 'Aurora',
    tags: ['formal', 'minimal'],
    sizes: womensSizes,
    price: 15800,
    stock: 12,
    images: [imagePool[0]],
  },
  {
    name: 'Aurora Pleat Trousers',
    brand: 'Lumen',
    genderLabel: 'womens' as GenderLabel,
    collection: 'Aurora',
    tags: ['formal', 'monotone'],
    sizes: womensSizes,
    price: 16800,
    stock: 10,
    images: [imagePool[1]],
  },
  {
    name: 'Aurora Wrap Blazer',
    brand: 'Lumen',
    genderLabel: 'womens' as GenderLabel,
    collection: 'Aurora',
    tags: ['formal', 'colorful'],
    sizes: womensSizes,
    price: 19800,
    stock: 8,
    images: [imagePool[2]],
  },
  {
    name: 'Aurora Glide Sneakers',
    brand: 'Lumen',
    genderLabel: 'unisex' as GenderLabel,
    collection: 'Aurora',
    tags: ['minimal', 'tech'],
    sizes: unisexSizes,
    price: 12800,
    stock: 20,
    images: [imagePool[3]],
  },
  {
    name: 'Pulse Mesh Top',
    brand: 'Beatline',
    genderLabel: 'mens' as GenderLabel,
    collection: 'Pulse',
    tags: ['street', 'colorful'],
    sizes: mensSizes,
    price: 9800,
    stock: 18,
    images: [imagePool[4]],
  },
  {
    name: 'Pulse Track Pants',
    brand: 'Beatline',
    genderLabel: 'mens' as GenderLabel,
    collection: 'Pulse',
    tags: ['street', 'sporty'],
    sizes: mensSizes,
    price: 11200,
    stock: 15,
    images: [imagePool[5]],
  },
  {
    name: 'Pulse Rhythm Jacket',
    brand: 'Beatline',
    genderLabel: 'unisex' as GenderLabel,
    collection: 'Pulse',
    tags: ['street', 'tech'],
    sizes: unisexSizes,
    price: 15200,
    stock: 11,
    images: [imagePool[6]],
  },
  {
    name: 'Pulse Neon Boots',
    brand: 'Beatline',
    genderLabel: 'womens' as GenderLabel,
    collection: 'Pulse',
    tags: ['street', 'colorful'],
    sizes: womensSizes,
    price: 13800,
    stock: 9,
    images: [imagePool[7]],
  },
  {
    name: 'Calm Linen Shirt',
    brand: 'Sereni',
    genderLabel: 'mens' as GenderLabel,
    collection: 'Calm',
    tags: ['minimal', 'monotone'],
    sizes: mensSizes,
    price: 11800,
    stock: 13,
    images: [imagePool[8]],
  },
  {
    name: 'Calm Wide Pants',
    brand: 'Sereni',
    genderLabel: 'unisex' as GenderLabel,
    collection: 'Calm',
    tags: ['minimal', 'vintage'],
    sizes: unisexSizes,
    price: 12600,
    stock: 14,
    images: [imagePool[9]],
  },
  {
    name: 'Calm Breeze Scarf',
    brand: 'Sereni',
    genderLabel: 'unisex' as GenderLabel,
    collection: 'Calm',
    tags: ['minimal', 'colorful'],
    sizes: ['Free'],
    price: 7200,
    stock: 22,
    images: [imagePool[10]],
  },
  {
    name: 'Calm Flow Loafers',
    brand: 'Sereni',
    genderLabel: 'mens' as GenderLabel,
    collection: 'Calm',
    tags: ['formal', 'minimal'],
    sizes: mensSizes,
    price: 14800,
    stock: 12,
    images: [imagePool[11]],
  },
  {
    name: 'Flux Shell Jacket',
    brand: 'Orbit',
    genderLabel: 'unisex' as GenderLabel,
    collection: 'Flux',
    tags: ['tech', 'sporty'],
    sizes: unisexSizes,
    price: 17600,
    stock: 17,
    images: [imagePool[0]],
  },
  {
    name: 'Flux Adaptive Pants',
    brand: 'Orbit',
    genderLabel: 'mens' as GenderLabel,
    collection: 'Flux',
    tags: ['tech', 'sporty'],
    sizes: mensSizes,
    price: 16400,
    stock: 16,
    images: [imagePool[1]],
  },
  {
    name: 'Flux Knit Tee',
    brand: 'Orbit',
    genderLabel: 'womens' as GenderLabel,
    collection: 'Flux',
    tags: ['tech', 'minimal'],
    sizes: womensSizes,
    price: 11800,
    stock: 21,
    images: [imagePool[2]],
  },
  {
    name: 'Flux Gravity Boots',
    brand: 'Orbit',
    genderLabel: 'unisex' as GenderLabel,
    collection: 'Flux',
    tags: ['tech', 'monotone'],
    sizes: unisexSizes,
    price: 18900,
    stock: 10,
    images: [imagePool[3]],
  },
  {
    name: 'Pulse Motion Tee',
    brand: 'Beatline',
    genderLabel: 'unisex' as GenderLabel,
    collection: 'Pulse',
    tags: ['street', 'sporty'],
    sizes: unisexSizes,
    price: 8800,
    stock: 25,
    images: [imagePool[4]],
  },
  {
    name: 'Aurora Duo Earrings',
    brand: 'Lumen',
    genderLabel: 'unisex' as GenderLabel,
    collection: 'Aurora',
    tags: ['minimal', 'colorful'],
    sizes: ['Free'],
    price: 6200,
    stock: 30,
    images: [imagePool[5]],
  },
  {
    name: 'Calm Harmony Cardigan',
    brand: 'Sereni',
    genderLabel: 'womens' as GenderLabel,
    collection: 'Calm',
    tags: ['vintage', 'minimal'],
    sizes: womensSizes,
    price: 13800,
    stock: 11,
    images: [imagePool[6]],
  },
  {
    name: 'Flux Wave Sunglasses',
    brand: 'Orbit',
    genderLabel: 'unisex' as GenderLabel,
    collection: 'Flux',
    tags: ['tech', 'minimal'],
    sizes: ['Free'],
    price: 9600,
    stock: 19,
    images: [imagePool[7]],
  },
  {
    name: 'Pulse Echo Scarf',
    brand: 'Beatline',
    genderLabel: 'unisex' as GenderLabel,
    collection: 'Pulse',
    tags: ['colorful', 'street'],
    sizes: ['Free'],
    price: 7600,
    stock: 24,
    images: [imagePool[8]],
  },
  {
    name: 'Aurora Flow Skirt',
    brand: 'Lumen',
    genderLabel: 'womens' as GenderLabel,
    collection: 'Aurora',
    tags: ['formal', 'colorful'],
    sizes: womensSizes,
    price: 15400,
    stock: 9,
    images: [imagePool[9]],
  },
  {
    name: 'Calm Balance Tee',
    brand: 'Sereni',
    genderLabel: 'mens' as GenderLabel,
    collection: 'Calm',
    tags: ['minimal', 'monotone'],
    sizes: mensSizes,
    price: 9200,
    stock: 18,
    images: [imagePool[10]],
  },
  {
    name: 'Flux Orbit Backpack',
    brand: 'Orbit',
    genderLabel: 'unisex' as GenderLabel,
    collection: 'Flux',
    tags: ['tech', 'minimal'],
    sizes: ['Free'],
    price: 14800,
    stock: 14,
    images: [imagePool[11]],
  },
  {
    name: 'Pulse Sync Bracelet',
    brand: 'Beatline',
    genderLabel: 'unisex' as GenderLabel,
    collection: 'Pulse',
    tags: ['street', 'colorful'],
    sizes: ['Free'],
    price: 5200,
    stock: 27,
    images: [imagePool[0]],
  },
];

async function main() {
  await prisma.savedBundle.deleteMany();
  await prisma.pairBundle.deleteMany();
  await prisma.matchRequest.deleteMany();
  await prisma.product.deleteMany();

  for (const product of products) {
    await prisma.product.create({
      data: product,
    });
  }

  console.log(`Seeded ${products.length} products.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
